### ISSUE TITLE
huggingface_hub.utils._errors.RepositoryNotFoundError

### ISSUE THREAD

**Issue by Yvonne-sq** [tmylla/NER_ZH#1]
Hi, do you have any opinions on this issue(huggingface-hub==0.9.1):

huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/api/models/D:%5Cyan%5Cyan_1%5Cstudio%5Clearning_assignment%5Cassignment_5%5CNER_ZH-master%5Cckpts%5Cbert-base-chinese. If the repo is private, make sure you are authenticated. (Request ID: Root=1-63c5fb3f-3fe26fc97bd19afb1f102692)

Invalid username or password.

**Comment by Yvonne-sq** [comment]
huggingface-hub==0.11.1:
Traceback (most recent call last):
  File "D:/yan/yan_1/studio/learning_assignment/assignment_5/NER_ZH-master/main.py", line 35, in <module>
    main()
  File "D:/yan/yan_1/studio/learning_assignment/assignment_5/NER_ZH-master/main.py", line 30, in main
    trainer_bbc = Bert_Bilstm_Crf(config, device, use_gpu, n_gpu, writer, id2label)
  File "D:\yan\yan_1\studio\learning_assignment\assignment_5\NER_ZH-master\trainer.py", line 24, in __init__
    do_lower_case=config.do_lower_case)
  File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py", line 1655, in from_pretrained
    local_files_only=local_files_only,
  File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py", line 3463, in get_fast_tokenizer_file
    path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
  File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\transformers\file_utils.py", line 1730, in get_list_of_files
    path_or_repo, revision=revision, token=token
  File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\huggingface_hub\utils\_validators.py", line 173, in validate_repo_id
    "Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are"
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\yan\yan_1\studio\learning_assignment\assignment_5\NER_ZH-master\ckpts\bert_bilstm_crf'.

**Comment by luyujie1** [comment]
Have you solved this problem? I'm having this problem now

**Comment by luyujie1** [comment]
> huggingface-hub==0.11.1: Traceback (most recent call last): File "D:/yan/yan_1/studio/learning_assignment/assignment_5/NER_ZH-master/main.py", line 35, in main() File "D:/yan/yan_1/studio/learning_assignment/assignment_5/NER_ZH-master/main.py", line 30, in main trainer_bbc = Bert_Bilstm_Crf(config, device, use_gpu, n_gpu, writer, id2label) File "D:\yan\yan_1\studio\learning_assignment\assignment_5\NER_ZH-master\trainer.py", line 24, in **init** do_lower_case=config.do_lower_case) File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py", line 1655, in from_pretrained local_files_only=local_files_only, File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py", line 3463, in get_fast_tokenizer_file path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\transformers\file_utils.py", line 1730, in get_list_of_files path_or_repo, revision=revision, token=token File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn validate_repo_id(arg_value) File "E:\Anaconda\Anaconda3-2019.10\envs\pytorch\lib\site-packages\huggingface_hub\utils_validators.py", line 173, in validate_repo_id "Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are" huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\yan\yan_1\studio\learning_assignment\assignment_5\NER_ZH-master\ckpts\bert_bilstm_crf'.

Have you solved this problem? I'm having this problem now
